name: Ghazaryan_Software_Prod

services: 
  postgres:
    image: postgres:18-alpine
    container_name: postgres_db_prod
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Vah.gh2005}
      POSTGRES_DB: ${POSTGRES_DB:-Ghazaryan_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-Ghazaryan_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.prod
    container_name: backend_prod
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-Vah.gh2005}@postgres:5432/${POSTGRES_DB:-Ghazaryan_DB}?schema=public"
      NODE_ENV: production
      PORT: 4000

  # Uncomment when frontend is ready
  # frontend:
  #   build:
  #     context: ../frontend
  #     dockerfile: Dockerfile
  #     target: production
  #   container_name: frontend_prod
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
  #   environment:
  #     NODE_ENV: production
  #     NEXT_PUBLIC_API_URL: http://backend:4000

volumes:
  postgres_data:
